CREATE TABLE IF NOT EXISTS public.ssra_public_catalog_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity TEXT NOT NULL DEFAULT 'courses',
  changed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

GRANT SELECT ON public.ssra_public_catalog_events TO anon, authenticated;
GRANT ALL ON public.ssra_public_catalog_events TO service_role;

ALTER TABLE public.ssra_public_catalog_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read catalog change events" ON public.ssra_public_catalog_events;
CREATE POLICY "Public can read catalog change events"
ON public.ssra_public_catalog_events
FOR SELECT
TO anon, authenticated
USING (true);

CREATE OR REPLACE FUNCTION public.bump_ssra_public_catalog_events()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.ssra_public_catalog_events (entity) VALUES ('courses');
  RETURN COALESCE(NEW, OLD);
END;
$$;

REVOKE ALL ON FUNCTION public.bump_ssra_public_catalog_events() FROM PUBLIC;

DROP TRIGGER IF EXISTS trg_bump_ssra_public_catalog_events ON public.ssra_courses;
CREATE TRIGGER trg_bump_ssra_public_catalog_events
AFTER INSERT OR UPDATE OR DELETE ON public.ssra_courses
FOR EACH ROW EXECUTE FUNCTION public.bump_ssra_public_catalog_events();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'ssra_public_catalog_events'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.ssra_public_catalog_events;
  END IF;
END $$;